version: 2.1

executors:
  windows-executor:
    machine:
      enabled: true
      image: windows-server-2019

jobs:
  say-hello:
    executor: windows-executor
    steps:
      - run:
          name: Say hello on Windows
          command: echo Hello, World!

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
