name: Runner

on:
  workflow_dispatch:

jobs:
  remote:
    runs-on: windows-latest
    timeout-minutes: 6

    steps:
      - name: Setup RDP + Ngrok background
        run: |
          Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
          Expand-Archive ngrok.zip
          Start-Process -NoNewWindow -FilePath ".\ngrok\ngrok.exe" -ArgumentList "tcp 3389"  # như nohup/start /b

      - name: Gọi lại scheduler.yml
        shell: pwsh
        run: |
          curl -X POST `
            -H "Authorization: token ${{ secrets.MY_PAT_TOKEN }}" `
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/scheduler.yml/dispatches `
            -d '{"ref":"main"}'
