name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-2025
    timeout-minutes: 6

    steps:
    - name: Download Ngrok
      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip

    - name: Extract
      run: Expand-Archive ngrok.zip

    - name: Auth
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable Terminal Services
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0

    - name: Enable Firewall
      run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Allow RDP Auth
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

    - name: Set Runner Password
      run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "Datnguyentv.com" -Force)

    - name: Start Ngrok in background (start /b)
      run: start /b "" .\ngrok\ngrok.exe tcp 3389
      shell: cmd

    - name: Force rerun at end
      if: ${{ always() }}
      shell: powershell
      run: |
        Start-Sleep -Seconds 5
        $runId = $Env:GITHUB_RUN_ID
        $repo = $Env:GITHUB_REPOSITORY
        $token = "${{ secrets.MY_PAT_TOKEN }}"
        $rerunUri = "https://api.github.com/repos/$repo/actions/runs/$runId/rerun"
        Write-Host "Triggering rerun..."
        Invoke-RestMethod -Headers @{Authorization = "token $token"} -Uri $rerunUri -Method POST
      env:
        GITHUB_RUN_ID: ${{ github.run_id }}
        GITHUB_REPOSITORY: ${{ github.repository }}
