name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-2025
    timeout-minutes: 6  # 6 phút cho chắc

    steps:
    - name: Download
      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip

    - name: Extract
      run: Expand-Archive ngrok.zip

    - name: Auth
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0

    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "Datnguyentv.com" -Force)

    - name: Create Tunnel
      run: .\ngrok\ngrok.exe tcp 3389

    - name: Auto rerun at 5 minutes
      if: ${{ always() }}
      shell: powershell
      run: |
        $runId = $Env:GITHUB_RUN_ID
        $repo = $Env:GITHUB_REPOSITORY
        $token = "${{ secrets.MY_PAT_TOKEN }}"
        $uri = "https://api.github.com/repos/$repo/actions/runs/$runId"
        $resp = Invoke-RestMethod -Headers @{Authorization = "token $token"} -Uri $uri
        $start = [datetime]$resp.created_at
        $now = Get-Date
        $runtime = $now - $start

        if ($runtime.TotalMinutes -ge 5) {
          Write-Host "Runtime $([math]::Round($runtime.TotalMinutes)) minutes, triggering rerun..."
          $rerunUri = "https://api.github.com/repos/$repo/actions/runs/$runId/rerun"
          Invoke-RestMethod -Headers @{Authorization = "token $token"} -Uri $rerunUri -Method POST
        } else {
          Write-Host "Runtime $([math]::Round($runtime.TotalMinutes)) minutes, no rerun needed."
        }
      env:
        GITHUB_RUN_ID: ${{ github.run_id }}
        GITHUB_REPOSITORY: ${{ github.repository }}
