name: Scheduler

on:
  workflow_dispatch:

jobs:
  restart:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Delay + Restart
        run: |
          echo "Sleeping..."
          sleep 180
          echo "Triggering Runner workflow"
          curl -X POST \
            -H "Authorization: token ${{ secrets.MY_PAT_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/main.yml/dispatches \
            -d '{"ref":"main"}'
